import React from 'react';
import {AbsoluteFill, Easing, interpolate, Sequence, useCurrentFrame} from 'remotion';
import {z} from 'zod';
import {EndCredits} from './lib/EndCredits';
import {FlightCrate} from './lib/clinic';
import {Gate} from './lib/civics';
import {AlaskaMini} from './lib/kit';
import {Nameplate, StatCard} from './lib/props';
import {BushPlane} from './lib/vehicles';
import {VoiceProvider} from './lib/voice';

const W=1080,H=1920,CAPTION_TOP=1336,CAPTION_H=132;
const CREAM='#F6E7C8',PAPER='#FFF8EC',SPRUCE='#315F59',PLUM='#3B1837',BERRY='#8B2F58',GOLD='#D7A83E',GRAPHITE='#596363',INK='#182322';
const FONT='Archivo, Arial, sans-serif',MONO='JetBrains Mono, monospace';
const ease=(f:number,a=4,d=24)=>interpolate(f,[a,a+d],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.2,.8,.2,1)});
const SVG:React.FC<{children:React.ReactNode}>=({children})=><svg width={W} height={H} viewBox="0 0 1080 1920" style={{position:'absolute',inset:0,overflow:'visible'}}>{children}</svg>;
const Fit:React.FC<{text:string;x?:number;y:number;size?:number;width?:number;color?:string;mono?:boolean}>=({text,x=540,y,size=48,width=900,color=INK,mono=false})=><text x={x} y={y} textAnchor="middle" fill={color} fontFamily={mono?MONO:FONT} fontWeight={900} fontSize={Math.max(17,Math.min(size,width/(Math.max(1,text.length)*.59)))}>{text}</text>;
const Plate:React.FC<{text:string;y:number;color?:string;width?:number}>=({text,y,color=PAPER,width=850})=><g><rect x={540-width/2+7} y={y-38+8} width={width} height={60} rx={9} fill={PLUM} opacity={.22}/><rect x={540-width/2} y={y-38} width={width} height={60} rx={9} fill={color} stroke={INK} strokeWidth={4}/><Fit text={text} y={y+1} size={27} width={width-28} mono/></g>;
const CLAIM_STRIPS:Record<number,string[]>={
  1:['ROADLESS COMMUNITIES'],
  3:['RYAN AIR PROPOSAL · AUTONOMOUS CARGO DRONES + EVTOL','CARGO DRONES · PHARMACEUTICALS','ELECTRIC AIRCRAFT · PATIENTS + PROVIDERS'],
  6:['NO PURCHASE · NO FAA APPROVAL · NO COMPLETED FLIGHT DOCUMENTED','NO ROUTE DOCUMENTED'],
  7:['SUMMARY · BETHEL + DILLINGHAM REGIONS','SERVICE FIELD · ANCHORAGE · BRISTOL BAY · DILLINGHAM · YUKON-KOYUKUK'],
  8:['CARGO TEST · FAA PART 135 + OPERATING AUTHORIZATION','PASSENGER TEST · AIRCRAFT + PILOT + OPERATION'],
  10:['BUDGET FINALIZATION IN PROGRESS · AMOUNTS MAY CHANGE'],
};
const EvidenceStrips:React.FC<{n:number}>=({n})=>{const rows=CLAIM_STRIPS[n]||[];return <g>{rows.map((text,i)=><g key={text}><rect x={45} y={1250+i*27} width={990} height={24} rx={5} fill={PLUM} opacity={.9}/><Fit text={text} y={1268+i*27} size={18} width={960} color={PAPER} mono/></g>)}</g>};

const World:React.FC<{f:number;n:number}>=({f,n})=><SVG><defs><linearGradient id="sky0911" x2="0" y2="1"><stop stopColor={n>=10?'#FFF7E8':'#E9DDC1'}/><stop offset=".65" stopColor={CREAM}/><stop offset="1" stopColor="#C9B58D"/></linearGradient><pattern id="fiber0911" width="78" height="62" patternUnits="userSpaceOnUse"><path d="M0 28Q19 8 39 28T78 28" fill="none" stroke={SPRUCE} strokeWidth="2" opacity=".08"/></pattern></defs><rect data-band="ok" width={W} height={H} fill="url(#sky0911)"/><rect data-band="ok" x={30} y={360} width={1020} height={900} rx={32} fill="url(#fiber0911)"/><path d={`M0 ${1230+5*Math.sin(f/45)}Q250 1175 510 1230T1080 1215V1336H0Z`} fill="#8B7654" opacity={.8}/>{Array.from({length:10},(_,i)=><path key={i} d={`M${i*125-20} 1180l55-110 55 110`} fill={SPRUCE} opacity={.16+(i%3)*.04}/>)}</SVG>;
const Road:React.FC<{roll:number}>=({roll})=><g><path d={`M110 1240H${860-520*roll}`} stroke="#6E5031" strokeWidth={118} strokeLinecap="round"/><path d={`M110 1218H${860-520*roll}`} stroke="#B18B58" strokeWidth={72} strokeDasharray="52 18"/><circle cx={860-520*roll} cy={1229} r={58} fill="#6E5031" stroke={INK} strokeWidth={8}/></g>;
const Lamps:React.FC<{p:number}>=({p})=><g>{['ROUTE','FAA','REPEAT','CLINIC','ARRIVAL'].map((s,i)=><g key={s} transform={`translate(${180+i*180},1040) scale(${ease(p*60,i*5,18)})`}><circle r={28} fill={PAPER} stroke={GRAPHITE} strokeWidth={8}/><Fit text={s} x={0} y={72} size={20} width={150} mono/></g>)}</g>;
const HEADS=['OVER THE MISSING ROAD','A PRELIMINARY SHEET','SAME AWARD. DIFFERENT PROOF.','A WORKING NETWORK','FIRST, ONE MEDICINE BOX','WHAT THE NOTICE DOES NOT SHOW','THE MAP IS UNSETTLED','THE SECOND LADDER','CARGO IS NOT PASSENGER PROOF','THE AMOUNT MAY CHANGE','NAME THE TEST','STILL IN THE CRATE'];
type Beat={id:number;at:number;label:string};
const Shot:React.FC<{n:number;from:number;dur:number;beats:Beat[]}>=({n,from,dur})=>{const f=useCurrentFrame(),g=f+from,p=ease(f),q=ease(f,28,22),travel=interpolate(f,[0,Math.max(1,dur)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.ease)});let art:React.ReactNode;
  if(n===1) art=<g><Road roll={p}/><FlightCrate x={540} y={1130} f={g} scale={1.15} proposed tag="" groundY={1240}/><Plate text="$4 MILLION MEETS THE ROAD EDGE" y={560} color={PAPER}/></g>;
  else if(n===2) art=<g><g transform={`translate(0 ${100*(1-p)})`} opacity={p}><rect x={110} y={520} width={860} height={610} rx={24} fill={PAPER} stroke={INK} strokeWidth={8}/><Nameplate x={540} y={610} text="ALASKA DOH · RYAN AIR" sub="PROJECTED · PRELIMINARY"/><StatCard x={540} y={850} big="$4,171,115" sub="PROJECTED PRELIMINARY AWARD" color={BERRY} scale={1.35}/></g><g opacity={ease(f,190,16)} transform={`translate(825 1085) rotate(${-10+10*ease(f,190,16)}) scale(${.4+.6*ease(f,190,16)})`}><circle r={82} fill={GOLD} stroke={INK} strokeWidth={7}/><Fit text="PROJECTED" x={0} y={8} size={21} width={142} mono/></g><FlightCrate x={540} y={1150} f={g} scale={.68} proposed/></g>;
  else if(n===3) art=<g><path d="M540 560V1200" stroke={PLUM} strokeWidth={14}/><g transform={`translate(${-80+80*p},0)`}><Plate text="AUTONOMOUS · CARGO DRONES" y={700} width={430}/><FlightCrate x={300} y={1050} f={g} scale={.7} proposed/></g><g transform={`translate(${80-80*p},0)`}><Plate text="EVTOL · PATIENTS + PROVIDERS" y={820} width={440}/><path d="M730 1010q70-110 140 0v120H730Z" fill={PAPER} stroke={INK} strokeWidth={8}/></g></g>;
  else if(n===4) art=<g><AlaskaMini frame={g} x={540} y={870} scale={2.3} pin/><g transform={`translate(${-260+1380*travel},760) scale(.95)`}><BushPlane x={0} y={0} f={g} mode="fly" body={SPRUCE}/></g><FlightCrate x={540} y={1130} f={g} scale={.72} proposed/><Plate text="RYAN AIR SAYS · 24 AIRCRAFT · 8 HUBS · 70+ VILLAGES" y={560}/></g>;
  else if(n===5) art=<g><FlightCrate x={540} y={950} f={g} scale={1.45} proposed latchProgress={p}/><path d={`M230 610Q540 ${480-55*q} 850 610`} fill="none" stroke={SPRUCE} strokeWidth={12} strokeDasharray="20 14"/><Plate text="ROUTE · AUTHORIZATION · NOT YET PROVED" y={1215}/></g>;
  else if(n===6) art=<g>{['PURCHASE','FAA APPROVAL','ROUTE','COMPLETED FLIGHT'].map((s,i)=>{const denied=ease(f,90+i*45,12);return <g key={s} transform={`translate(${180+(i%2)*480},${650+Math.floor(i/2)*280})`} opacity={ease(f,i*7,18)}><rect width={240} height={150} rx={12} fill={PAPER} stroke={INK} strokeWidth={7}/><rect width={240} height={150} rx={12} fill={BERRY} opacity={.24*denied}/><rect x={28} y={58} width={46} height={46} fill="none" stroke={GRAPHITE} strokeWidth={6}/><path d="M35 65l32 32M67 65L35 97" stroke={BERRY} strokeWidth={9} strokeLinecap="round" opacity={denied}/><Fit text={s} x={130} y={125} size={22} width={190} mono/></g>})}<FlightCrate x={540} y={1200} f={g} scale={.62} proposed/></g>;
  else if(n===7) art=<g><g transform={`translate(${-60+60*p},0)`}><rect x={90} y={560} width={420} height={560} rx={22} fill={PAPER} stroke={INK} strokeWidth={7}/><Fit text="SUMMARY" x={300} y={650} size={32} width={340} mono/><Fit text="BETHEL" x={300} y={810} size={44} width={340}/><Fit text="DILLINGHAM" x={300} y={910} size={44} width={340}/></g><g transform={`translate(${60-60*p},0)`}><rect x={570} y={500} width={420} height={680} rx={22} fill={PAPER} stroke={INK} strokeWidth={7}/><Fit text="SEPARATE FIELD" x={780} y={590} size={30} width={350} mono/>{['ANCHORAGE','BRISTOL BAY','DILLINGHAM','YUKON-KOYUKUK'].map((s,i)=><Fit key={s} text={s} x={780} y={730+i*90} size={30} width={340}/>)}</g><FlightCrate x={540} y={1240} f={g} scale={.48} proposed/></g>;
  else if(n===8) art=<g><path d="M140 1120H500" stroke={SPRUCE} strokeWidth={18}/><FlightCrate x={315} y={1050} f={g} scale={.62} proposed/><Fit text="CARGO TEST" x={315} y={1195} size={28} width={330} mono/>{['AIRCRAFT','PILOT','OPERATION'].map((s,i)=><g key={s} transform={`translate(720,${1040-i*220})`}><Gate f={g} x={0} y={0} scale={.62} condition={s} verdict="asking" swing={p*.18}/></g>)}<Fit text="PEOPLE TEST" x={720} y={1195} size={28} width={330} mono/></g>;
  else if(n===9) art=<g><FlightCrate x={270} y={690} f={g} scale={.72} proposed latchProgress={p}/><path d="M315 820Q470 720 585 870" fill="none" stroke={SPRUCE} strokeWidth={11} strokeDasharray="18 13"/><Gate f={g} x={690} y={990} condition="PASSENGER OPERATION" verdict="block" swing={0} scale={1.1}/><g transform={`translate(${240+310*Math.min(1,p*1.4)},920) rotate(${-7*q})`}><rect x={-130} y={-70} width={260} height={140} rx={12} fill={PAPER} stroke={INK} strokeWidth={7}/><Fit text="CARGO EVIDENCE" x={0} y={12} size={27} width={230} mono/></g><g opacity={q}><rect x={300} y={1080} width={480} height={95} rx={8} fill={BERRY} stroke={INK} strokeWidth={6}/><Fit text="WRONG TEST" y={1142} size={52} width={420} color={PAPER}/></g></g>;
  else if(n===10) art=<g><rect x={120} y={560} width={840} height={570} rx={28} fill={PAPER} stroke={INK} strokeWidth={8}/><Fit text="BUDGET FINALIZATION" y={690} size={53}/><Fit text="IN PROGRESS" y={770} size={53}/><g transform={`translate(${40*Math.sin(f/10)},0)`}><StatCard x={540} y={940} big="$4,171,115" sub="PROJECTED AMOUNTS MAY CHANGE" color={BERRY} scale={1.28}/></g><FlightCrate x={540} y={1210} f={g} scale={.55} proposed/></g>;
  else if(n===11) art=<g><FlightCrate x={540} y={870} f={g} scale={1.15} proposed latchProgress={p}/><Lamps p={p}/><path d="M160 1180H920" stroke={SPRUCE} strokeWidth={12} strokeDasharray="22 14"/><Plate text="FAA CERTIFICATION + OPERATING AUTHORIZATION" y={1240}/></g>;
  else art=<g><Road roll={1}/><FlightCrate x={540} y={1095} f={g} scale={1.2} proposed tag="" groundY={1240}/><g opacity={q}><Plate text="NAME THE FIRST ROUTE" y={620}/></g><Fit text="FUTURE · STILL IN THE CRATE" y={1288} size={34} width={800} color={PLUM} mono/></g>;
  const cam=n===2?`translateY(${55-110*travel}px)`:n===3?`translateY(${50-100*travel}px)`:n===4?`translateX(${-70+140*travel}px)`:n===7?`translateY(${32-64*travel}px)`:n===8?`scale(${1+.025*travel})`:n===9?`translateY(${35-70*travel}px)`:n===12?`scale(${1+.045*travel})`:`translateY(${10-20*travel}px)`;
  return <AbsoluteFill><AbsoluteFill style={{transform:cam,transformOrigin:'540px 900px'}}><World f={g} n={n}/><SVG><Fit text="ALASKA.AI / DISPATCH" y={250} size={31} color={SPRUCE} mono/><Fit text="SEPTEMBER 11, 2026" y={300} size={20} color={PLUM} mono/><Fit text={HEADS[n-1]} y={480} size={40} width={910}/>{art}<EvidenceStrips n={n}/></SVG></AbsoluteFill></AbsoluteFill>;
};
const Captions:React.FC<{cues:{t:number;d:number;text:string}[]}>=({cues})=>{const f=useCurrentFrame(),c=cues.find(x=>f/30>=x.t&&f/30<x.t+x.d);if(!c)return null;const words=c.text.split(/\s+/);let cut=Math.ceil(words.length/2),best=Infinity;for(let i=1;i<words.length;i++){const score=Math.max(words.slice(0,i).join(' ').length,words.slice(i).join(' ').length);if(score<best){best=score;cut=i;}}const rows=c.text.length<=38?[c.text]:[words.slice(0,cut).join(' '),words.slice(cut).join(' ')],size=Math.min(40,950/(Math.max(...rows.map(x=>x.length))*.58));return <AbsoluteFill><SVG><rect data-band="ok" x={0} y={CAPTION_TOP} width={W} height={CAPTION_H} fill={PLUM}/>{rows.map((s,i)=><text data-band="ok" key={i} x={540} y={CAPTION_TOP+(rows.length===1?80:50)+i*47} textAnchor="middle" fontFamily={FONT} fontSize={size} fontWeight={850} fill={PAPER}>{s}</text>)}</SVG></AbsoluteFill>};
export const ep0911Schema=z.object({captions:z.array(z.object({t:z.number(),d:z.number(),text:z.string()})).optional(),scenes:z.array(z.object({from:z.number(),dur:z.number()})).optional(),total:z.number().optional(),lines:z.array(z.number()).optional(),beats:z.array(z.object({id:z.number(),at:z.number(),label:z.string()})).optional(),credits:z.any().optional(),mouth:z.any().optional(),accents:z.any().optional()});
export const Ep0911:React.FC<z.infer<typeof ep0911Schema>>=({captions=[],scenes=[],total=3900,beats=[],credits,mouth=[],accents=[]})=>{const end=total-(credits?.frames??195);return <VoiceProvider data={{fps:30,mouth,accents}}><AbsoluteFill style={{backgroundColor:CREAM}}>{scenes.map((s,i)=><Sequence key={i} from={s.from} durationInFrames={s.dur} name={`S${i+1}`}><Shot n={i+1} from={s.from} dur={s.dur} beats={beats}/></Sequence>)}<Captions cues={captions}/>{credits&&<Sequence from={end} durationInFrames={credits.frames} name="CREDITS"><EndCredits data={credits} durationInFrames={credits.frames}/></Sequence>}</AbsoluteFill></VoiceProvider>};
